server:
  # 项目端口号
  port: 8080
  servlet:
    # 统一前缀
    context-path: /flowable-demo


spring:
  application:
    name: flowable-demo
  datasource:
    url: jdbc:mysql://139.155.77.158:3306/flowable-demo?nullCatalogMeansCurrent=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 512

flowable:
  database-schema-update: true
  check-process-definitions: true
  process-definition-location-prefix: classpath:/
  history-level: activity
  db-history-used: true
  idm:
    enabled: false
  cmmn:
    enabled: false
  dmn:
    enabled: false
  rest-api-enabled: false
  process:
    definition-cache-limit: 500
  async-executor-activate: true
  async-history-executor-activate: false

